name: 'c_action'
description: 'Checks length >= 80 chars'
author: 'Arthur Wambst'

#inputs:
  #   token:
  #   description: “Username”
  #required: false
inputs:
  token:
   description: “secret token”
   required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: run line_length.sh
      run: line_length.sh >> col_excess.txt
      shell: bash
    - uses: LouisBrunner/checks-action@latest
      if: always()
      with:
        token: ${{ inputs.token }}
        name: Code coverage
        conclusion: ${{ job.status }}
        output: '{"summary":"Code coverage"}'
        output_text_description_file: col_excess.txt
