name: 'c_action'
description: 'Checks length >= 80 chars'
author: 'Arthur Wambst'

inputs:
  token:
   description: “Username”
   required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - run: |
      for a in $(find $PWD | grep -E "\.c$|\.h$")
do
        ((PARSED = 0))
        ((LINE = 0))
        for b in $(awk '{print length}' $a)
        do
                ((LINE += 1))
                if (($b >= 80));        then
                        if ((PARSED == 0)); then
                                echo "$a :"
                                ((PARSED = 1));
                        fi
                        echo "l.$LINE too long ( $b cols )";
                fi;
        done
done >> result.txt
      shell: bash
    - run: ls
      shell: bash
    - run: pwd
      shell: bash

