name: 'c_action'
description: 'Checks length >= 80 chars'
author: 'Arthur Wambst'

#inputs:
  #   token:
  #   description: “Username”
  #required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - run: ls
      shell: bash
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: run line_length.sh
      run: line_length.sh
      shell: bash
    - run: ls
      shell: bash
    - run: pwd
      shell: bash

