name: 'c_action'
description: 'Checks length >= 80 chars'
author: 'Arthur Wambst'

#inputs:
  #   token:
  #   description: “Username”
  #required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - run: ls
      shell: bash
    - run: ./line_length.sh
      shell: bash
    - run: ls
      shell: bash
    - run: pwd
      shell: bash

