name: 'c_action'
description: 'Checks length >= 80 chars'
author: 'Arthur Wambst'

inputs:
  token:
   description: “Username”
   required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - run: ./testBash.bash < result.txt
      shell: bash
    - run: ls
      shell: bash
    - run: pwd
      shell: bash

